### ISSUE TITLE
No "exports" main defined in `.../node_modules/@gerrit0/mini-shiki/package.json`

### ISSUE THREAD

**Issue by B4nan** [Gerrit0/mini-shiki#1] opened 2024-11-29 07:17 UTC
We use typodoc inside docusaurus via https://github.com/milesj/docusaurus-plugin-typedoc-api, and the latest update of typedoc [broke our pipelines](https://github.com/mikro-orm/mikro-orm/actions/runs/12075851011/job/33676312701?pr=6259), probably because of adoption of this new package. Did a quick search, and its most likely because that package is ESM, and I am honestly puzzled that you were previously depending on shiki which was also ESM, but typedoc is not, right? I checked the original shiki exports field but it looks quite similar, not sure what exactly this is about.

```
Error:  Error: Unable to build website for locale en.
    at tryToBuildLocale (/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/@docusaurus/core/lib/commands/build/build.js:78:15)
    at async /home/runner/work/mikro-orm/mikro-orm/docs/node_modules/@docusaurus/core/lib/commands/build/build.js:34:9
    ... 4 lines matching cause stack trace ...
    at async file:///home/runner/work/mikro-orm/mikro-orm/docs/node_modules/@docusaurus/core/bin/docusaurus.mjs:44:3 {
  [cause]: Error: Docusaurus could not load module at path "/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/docusaurus-plugin-typedoc-api/lib/index.js"
  Cause: No "exports" main defined in /home/runner/work/mikro-orm/mikro-orm/docs/node_modules/@gerrit0/mini-shiki/package.json
      at loadFreshModule (/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/@docusaurus/utils/lib/moduleUtils.js:36:15)
      at normalizePluginConfig (/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/@docusaurus/core/lib/server/plugins/configs.js:44:65)
      at /home/runner/work/mikro-orm/mikro-orm/docs/node_modules/@docusaurus/core/lib/server/plugins/configs.js:98:60
      at Array.map (<anonymous>)
      at loadPluginConfigs (/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/@docusaurus/core/lib/server/plugins/configs.js:98:38)
      at async initPlugins (/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/@docusaurus/core/lib/server/plugins/init.js:127:27)
      at async /home/runner/work/mikro-orm/mikro-orm/docs/node_modules/@docusaurus/core/lib/server/plugins/plugins.js:137:36
      at async loadSite (/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/@docusaurus/core/lib/server/site.js:144:45)
      at async buildLocale (/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/@docusaurus/core/lib/commands/build/buildLocale.js:28:18)
      at async runBuildLocaleTask (/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/@docusaurus/core/lib/commands/build/build.js:93:5)
      at async /home/runner/work/mikro-orm/mikro-orm/docs/node_modules/@docusaurus/core/lib/commands/build/build.js:74:13
      at async tryToBuildLocale (/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/@docusaurus/core/lib/commands/build/build.js:70:9)
      at async /home/runner/work/mikro-orm/mikro-orm/docs/node_modules/@docusaurus/core/lib/commands/build/build.js:34:9
      at async mapAsyncSequential (/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/@docusaurus/utils/lib/jsUtils.js:21:24)
      at async Command.build (/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/@docusaurus/core/lib/commands/build/build.js:[33](https://github.com/mikro-orm/mikro-orm/actions/runs/12075851011/job/33676312701?pr=6259#step:9:38):5)
      at async Promise.all (index 0)
      at async runCLI (/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/@docusaurus/core/lib/commands/cli.js:56:5)
      at async file:///home/runner/work/mikro-orm/mikro-orm/docs/node_modules/@docusaurus/core/bin/docusaurus.mjs:44:3 {
    [cause]: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /home/runner/work/mikro-orm/mikro-orm/docs/node_modules/@gerrit0/mini-shiki/package.json
        at exportsNotFound (node:internal/modules/esm/resolve:296:10)
        at packageExportsResolve (node:internal/modules/esm/resolve:586:13)
        at resolveExports (node:internal/modules/cjs/loader:640:36)
        at Function._findPath (node:internal/modules/cjs/loader:748:31)
        at Function._resolveFilename (node:internal/modules/cjs/loader:12[35](https://github.com/mikro-orm/mikro-orm/actions/runs/12075851011/job/33676312701?pr=6259#step:9:40):27)
        at Function.resolve (node:internal/modules/helpers:151:19)
        at _resolve (/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/jiti/dist/jiti.js:1:241814)
        at jiti (/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/jiti/dist/jiti.js:1:244531)
        at /home/runner/work/mikro-orm/mikro-orm/docs/node_modules/typedoc/dist/lib/utils/highlighter.js:1:554
        at evalModule (/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/jiti/dist/jiti.js:1:247313)
        at jiti (/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/jiti/dist/jiti.js:1:245241)
        at /home/runner/work/mikro-orm/mikro-orm/docs/node_modules/typedoc/dist/lib/utils/options/sources/typedoc.js:10:20
        at evalModule (/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/jiti/dist/jiti.js:1:247313)
        at jiti (/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/jiti/dist/jiti.js:1:245241)
        at /home/runner/work/mikro-orm/mikro-orm/docs/node_modules/typedoc/dist/lib/utils/options/sources/index.js:1:282
        at evalModule (/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/jiti/dist/jiti.js:1:247313)
        at jiti (/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/jiti/dist/jiti.js:1:245241)
        at /home/runner/work/mikro-orm/mikro-orm/docs/node_modules/typedoc/dist/lib/utils/options/options.js:5:14
        at evalModule (/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/jiti/dist/jiti.js:1:247313)
        at jiti (/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/jiti/dist/jiti.js:1:245241)
        at /home/runner/work/mikro-orm/mikro-orm/docs/node_modules/typedoc/dist/lib/utils/options/index.js:1:1479
        at evalModule (/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/jiti/dist/jiti.js:1:247313)
        at jiti (/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/jiti/dist/jiti.js:1:245241)
        at /home/runner/work/mikro-orm/mikro-orm/docs/node_modules/typedoc/dist/lib/utils/index.js:10:14
        at evalModule (/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/jiti/dist/jiti.js:1:247313)
        at jiti (/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/jiti/dist/jiti.js:1:245241)
        at /home/runner/work/mikro-orm/mikro-orm/docs/node_modules/typedoc/dist/lib/models/comments/comment.js:35:14
        at evalModule (/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/jiti/dist/jiti.js:1:247313)
        at jiti (/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/jiti/dist/jiti.js:1:245241)
        at /home/runner/work/mikro-orm/mikro-orm/docs/node_modules/typedoc/dist/lib/models/reflections/abstract.js:35:16
        at evalModule (/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/jiti/dist/jiti.js:1:247313)
        at jiti (/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/jiti/dist/jiti.js:1:245241)
        at /home/runner/work/mikro-orm/mikro-orm/docs/node_modules/typedoc/dist/lib/models/reflections/index.js:1:2263
        at evalModule (/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/jiti/dist/jiti.js:1:247313)
        at jiti (/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/jiti/dist/jiti.js:1:245241)
        at /home/runner/work/mikro-orm/mikro-orm/docs/node_modules/typedoc/dist/lib/models/index.js:1:151
        at evalModule (/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/jiti/dist/jiti.js:1:247313)
        at jiti (/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/jiti/dist/jiti.js:1:245241)
        at /home/runner/work/mikro-orm/mikro-orm/docs/node_modules/typedoc/dist/lib/serialization/deserializer.js:2:14
        at evalModule (/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/jiti/dist/jiti.js:1:247313)
        at jiti (/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/jiti/dist/jiti.js:1:245241)
        at /home/runner/work/mikro-orm/mikro-orm/docs/node_modules/typedoc/dist/lib/serialization/index.js:1:550
        at evalModule (/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/jiti/dist/jiti.js:1:247313)
        at jiti (/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/jiti/dist/jiti.js:1:245241)
        at /home/runner/work/mikro-orm/mikro-orm/docs/node_modules/typedoc/dist/lib/application.js:[37](https://github.com/mikro-orm/mikro-orm/actions/runs/12075851011/job/33676312701?pr=6259#step:9:42):14
        at evalModule (/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/jiti/dist/jiti.js:1:247313)
        at jiti (/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/jiti/dist/jiti.js:1:245241)
        at /home/runner/work/mikro-orm/mikro-orm/docs/node_modules/typedoc/dist/index.js:4:20
        at evalModule (/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/jiti/dist/jiti.js:1:247313)
        at jiti (/home/runner/work/mikro-orm/mikro-orm/docs/node_modules/jiti/dist/jiti.js:1:2452[41](https://github.com/mikro-orm/mikro-orm/actions/runs/12075851011/job/33676312701?pr=6259#step:9:46)) {
      code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
    }
  }
}
```

**Comment by B4nan** [comment] 2024-11-29 07:35
> Convert to ESM to enable easier use of ESM-only dependencies.

Huh, missed the typodoc 0.27 changelog, this kinda explains it. If you know it's about that, feel free to close it, sorry for the noise. It will take some time for me to move our docs to ESM, but its on the roadmap.

I'd also suggest you make this note more prominent (readme, docs) instead of just hiding it in the changelog :]

**Comment by Gerrit0** [comment] 2024-11-29 15:36
I'm pretty sure that the cause of this is that `docusaurus-plugin-typedoc-api` is not ESM.

I just verified that Shiki does not actually use async ESM, so the `--experimental-require-module` flag should allow using this package from CJS (once the import spec is relaxed). I just published 1.24.1, which you should be able to get by reinstalling without a lockfile, and might make your build work again if you pass that flag to Node or run with Node 23, where it is enable by default.

The changelog is exactly the right place for this type of information on breaking changes -- that's the entire point of that file!

**Comment by B4nan** [comment] 2024-11-29 16:02
Thank you! My only issue is that I want to test the build works via PR checks and I need to run them on older node versions too, but it's fine to run the docs check only on node 22 I guess, so not really a problem if it's just about that.

Btw, I am not saying you should remove it from changelog, just that you should maybe highlight it on other places too, since moving to ESM only is quite a big deal for downstream. I have no issues with that move itself, I plan to do it with my packages too during next year, the time is now given the unflagged `require(esm)` which will land to node 20 too at some point.

**Comment by Gerrit0** [comment] 2024-11-29 16:37
`require(esm)` is in Node 20.17

**Comment by B4nan** [comment] 2024-11-29 17:02
I meant the unflagging

**Comment by Gerrit0** [comment] 2024-12-13 21:57
Closing this as this package can now be `require`d

**Closed as completed by Gerrit0** 2024-12-13 21:57 UTC
